### ISSUE TITLE
Q:Any chance wanko will run under windows?

### ISSUE THREAD

**Issue by Andrey-dc** [kemonomachi/wanko#1]
I have installed Ruby with rubyinstaller-2.3.3.
And when i try to run wanko.rb this comes out:
K:\Ruby23\Apps\wanko-master\lib>ruby wanko.rb
```
k:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': ca
nnot load such file -- wanko/data (LoadError)
        from k:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from wanko.rb:1:in `<main>'
```

Am i not using it right or wanko is not expected to run in windows environment?

**Comment by kemonomachi** [comment]
`wanko` is written mainly for Linux, yes. It might run under Windows as well, but I haven't tested it.

The code is also meant to be built and installed as a gem, but I see that I never actually published one anywhere. I'll see if I can push it to rubygems, or at least update the README.

**Comment by kemonomachi** [comment]
I've pushed a gem to RubyGems now, had to change the name due to a name collision. You can install it with the gem command: `gem install kemonomachi-wanko`. If your PATH has been set up correctly, you should then be able to run the `wanko` command directly. Try this, and open a new issue if it still doesn't work. Running it under [Cygwin](https://www.cygwin.com/) might also be an option.
